version: '3.5'

services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    #volumes:
    #  - ./postgres/data:/var/lib/postgresql/data

  web1:
    container_name: web1
    build: ./myproject
    command: sh /code/run.sh
    volumes:
      - ./myproject:/code
    depends_on:
      - db

  nginx:
      container_name: nginx
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/:/etc/nginx/conf.d/
        - ./myproject:/code
      depends_on:
        - web1